# Generated by Django 3.2.3 on 2021-05-30 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist_app', '0006_auto_20210530_2353'),
    ]

    operations = [
        migrations.RenameField(
            model_name='watchlist',
            old_name='number_reviews',
            new_name='number_ratings',
        ),
    ]
